# Travis Continuous Integration
# Mamba links:
# https://mamba.readthedocs.io/en/latest/installation.html
# Sample travis file:
# https://conda.pydata.org/docs/travis.html
# Avoiding duplicate branch-pr triggers:
# https://github.com/travis-ci/travis-ci/issues/1147#issuecomment-160820262
dist: xenial
branches:
  only:
    - master
language: python
notifications:
  email: false

python:
  - "3.7"

before_install:
  - |
        MODIFIED_FILES=$(git diff --name-only "$TRAVIS_COMMIT_RANGE" 2>/dev/null)
        if [ $? -eq 0 ] && ! echo "$MODIFIED_FILES" | grep -qvE '(.md)|(.rst)|(.html)|(.png)|(.ico)'
          then
          echo "Only doc files were updated, not running the CI."
          exit
        fi
  - curl micro.mamba.pm/install.sh | bash
  - export PATH="$HOME/micromamba/bin:$PATH"
  - hash -r
  - micromamba shell init -s bash -p ~/micromamba
  - micromamba config set always_yes true
  - micromamba config set changeps1 false
  - micromamba config set show_channel_urls true

install:
  - micromamba env create --file ci/environment.yml
  - micromamba activate proplot-dev
  - micromamba list
  - which micromamba
  - which python
  - python setup.py sdist bdist_wheel
  - pip install --user ./dist/*.whl

script:
  - ci/run-linter.sh
