# Travis Continuous Integration
# For mamba links see https://mamba.readthedocs.io/en/latest/installation.html
# For sample travis file see https://conda.pydata.org/docs/travis.html
dist: xenial
language: python

notifications:
  email: false

python:
  - "3.7"

before_install:
  - |
        MODIFIED_FILES=$(git diff --name-only "$TRAVIS_COMMIT_RANGE" 2>/dev/null)
        if [ $? -eq 0 ] && ! echo "$MODIFIED_FILES" | grep -qvE '(.md)|(.rst)|(.html)|(.png)|(.ico)'
          then
          echo "Only doc files were updated, not running the CI."
          exit
        fi
  - curl micro.mamba.pm/install.sh | bash
  - export PATH="$HOME/micromamba/bin:$PATH"
  - hash -r
  - eval "$(micromamba shell hook --shell=bash)"
  - micromamba config set always_yes true
  - micromamba config set changeps1 false
  - micromamba config set show_channel_urls true

install:
  - micromamba env create --file ci/environment.yml
  - micromamba activate proplot-dev
  - micromamba list
  - which micromamba
  - which python
  - python setup.py sdist bdist_wheel
  - pip install --user ./dist/*.whl

script:
  - ci/run-linter.sh
